### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by Legion2** [TIK-NFL/ViPLab#2]
Was hat es mit `release_5_2m` und `release_5_2r` auf sich, was haben diese Kürzel zu bedeuten. Aus `release_5_2m` hab ich jetzt `release_5_2` gemacht, da der am aktuellsten war. Wird der `release_5_2r` noch gebraucht?

**Comment by bogenschlag** [comment]
Weiß ich nicht mehr, ist zu lange her (und war irgendein Ding von Thomas …), sorry – musst du dir im Zweifel aus einem Diff erschließen. 

`m` ist auf der Produktion ausgecheckt, insofern *vermute* ich, `r` wird nicht mehr benötigt.

Vielleicht hat @pascalseeland eine Idee.

**Comment by Legion2** [comment]
Auf der Produktion kann man `release_5_2` auschecken, dann kann `m` weg.

**Comment by Legion2** [comment]
`r` hab ich gelöscht, die gleichen Änderungen waren auch in `m` drin.
